// framework-integrations/vue/src/App.vue
<template>
  <h1>WCC Vue Integration Tests</h1>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- PROPS                                                              -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 1: Props (:count, label)</h2>
  <wcc-counter id="test1" :count="propCount" label="Static Label"></wcc-counter>
  <p>Vue propCount: {{ propCount }}</p>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- EVENTS                                                             -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 2: Events (@count-changed)</h2>
  <wcc-counter id="test2" :count="eventCount" @count-changed="eventCount = $event.detail"></wcc-counter>
  <p>Vue eventCount: {{ eventCount }}</p>
  <button @click="eventCount++">Vue increment (manual)</button>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- TWO-WAY BINDING (v-model)                                          -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 3: v-model:count (plugin)</h2>
  <wcc-counter id="test3" v-model:count="modelCount"></wcc-counter>
  <p>Vue modelCount: {{ modelCount }}</p>
  <button @click="modelCount++">Vue increment (v-model)</button>

  <h2>Test 4: v-model.trim (modifier)</h2>
  <wcc-counter id="test4" v-model:count.number="trimCount"></wcc-counter>
  <p>Vue trimCount: {{ trimCount }} (type: {{ typeof trimCount }})</p>

  <h2>Test 4b: Multiple v-model on same element</h2>
  <wcc-counter id="test4b" v-model:count="multiCount" v-model:label="multiLabel"></wcc-counter>
  <p>Vue multiCount: {{ multiCount }}, multiLabel: {{ multiLabel }}</p>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- DEFAULT SLOT                                                       -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 5: Default slot (children)</h2>
  <wcc-card id="test5">
    <p>Body content via default slot</p>
  </wcc-card>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- NAMED SLOTS                                                        -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 6: Named slots (template #name)</h2>
  <wcc-card id="test6">
    <template #header><strong>Header via #</strong></template>
    <p>Body content</p>
    <template #footer>Footer via #</template>
  </wcc-card>

  <h2>Test 7: Named slots (div slot="name")</h2>
  <wcc-card id="test7">
    <div slot="header"><strong>Bold</strong> header with <em>emphasis</em></div>
    <p>Body content</p>
    <div slot="footer">Footer with <a href="#">link</a></div>
  </wcc-card>

  <h2>Test 8: Named slots (template v-slot:name)</h2>
  <wcc-card id="test8">
    <template v-slot:header><strong>Header v-slot</strong></template>
    <p>Body content</p>
    <template v-slot:footer>Footer v-slot</template>
  </wcc-card>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- SCOPED SLOTS                                                       -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 9: Scoped slot (template #item="{ item, index }")</h2>
  <wcc-list id="test9">
    <template #item="{ item, index }">
      <li><strong>{{ index }}</strong>: {{ item }}</li>
    </template>
  </wcc-list>

  <h2>Test 10: Scoped slot (v-slot:item)</h2>
  <wcc-list id="test10">
    <template v-slot:item="{ item }">
      <li class="custom">★ {{ item }}</li>
    </template>
  </wcc-list>

  <h2>Test 11: Scoped slot + Vue interpolation coexistence</h2>
  <wcc-list id="test11">
    <template #item="{ item }">
      <li>{{ item }} (Vue says: {{ vueMessage }})</li>
    </template>
  </wcc-list>
</template>

<script setup>
import { ref } from 'vue'

const propCount = ref(10)
const eventCount = ref(0)
const modelCount = ref(0)
const trimCount = ref(0)
const multiCount = ref(0)
const multiLabel = ref('hello')
const vueMessage = ref('hello from Vue!')
</script>

// framework-testing/react/src/App.jsx
import React, { useRef, useState } from 'react'

export default function App() {
  const [message] = useState('hello from React!')

  return (
    <div>
      <h1>WCC React Integration Tests</h1>

      {/* Test 1: Named slot via string prop */}
      <h2>Test 1: Named slot (string prop)</h2>
      <wcc-card id="test1" header="Simple Header" footer="Simple Footer">
        <p>Body content via children</p>
      </wcc-card>

      {/* Test 2: Named slot via JSX prop */}
      <h2>Test 2: Named slot (JSX prop)</h2>
      <wcc-card id="test2"
        header={<h3>Header via JSX prop</h3>}
        footer={<span>Footer via JSX prop</span>}
      >
        <p>Body content 2</p>
      </wcc-card>

      {/* Test 3: Multiple named slots with nested elements */}
      <h2>Test 3: Named slots with nested elements</h2>
      <wcc-card id="test3"
        header={<div><strong>Bold</strong> header with <em>emphasis</em></div>}
        footer={<div>Footer with <a href="#">link</a></div>}
      >
        <p>Body 3</p>
      </wcc-card>

      {/* Test 4: Scoped slot (render prop) — single parameter */}
      <h2>Test 4: Scoped slot (single param)</h2>
      <wcc-list id="test4"
        renderItem={(item) => <li><strong>{item}</strong></li>}
      />

      {/* Test 5: Scoped slot (render prop) — multiple parameters */}
      <h2>Test 5: Scoped slot (multiple params)</h2>
      <wcc-list id="test5"
        renderItem={(item, index) => <li>{index}: {item}</li>}
      />

      {/* Test 6: Scoped slot with attributes */}
      <h2>Test 6: Scoped slot with class attribute</h2>
      <wcc-list id="test6"
        renderItem={(item) => <li className="custom-item">★ {item}</li>}
      />

      {/* Test 7: Passthrough props coexist with slot props */}
      <h2>Test 7: Passthrough props + slot props</h2>
      <wcc-card id="test7"
        data-testid="my-card"
        aria-label="Card component"
        header={<h3>Header 7</h3>}
      >
        <p>Body with passthrough props</p>
      </wcc-card>

      {/* Test 8: Event handlers preserved alongside slot props */}
      <h2>Test 8: Event handlers + slot props</h2>
      <wcc-card id="test8"
        onClick={() => console.log('clicked!')}
        header={<h3>Clickable Card</h3>}
      >
        <p>Click me (check console)</p>
      </wcc-card>

      {/* Test 9: ref preserved alongside slot props */}
      <h2>Test 9: ref + slot props</h2>
      <RefTest />
    </div>
  )
}

function RefTest() {
  const cardRef = useRef(null)

  return (
    <wcc-card id="test9"
      ref={cardRef}
      header={<h3>Card with ref</h3>}
    >
      <p>ref is preserved on the element</p>
    </wcc-card>
  )
}
