// framework-integrations/angular/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { WccSlotsDirective, WccSlotDef } from '../wcc-components_back/angular-adapter';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [WccSlotsDirective, WccSlotDef],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './app.component.html',
})
export class AppComponent {
  propCount = 10;
  eventCount = 0;
  modelCount = 0;
  multiCount = 0;
  multiLabel = 'hello';
  angularMessage = 'hello from Angular!';

  onCountChanged(event: Event) {
    this.eventCount = (event as CustomEvent).detail;
  }
}

<h1>WCC Angular Integration Tests</h1>

<!-- ═══════════════════════════════════════════════════════════════════ -->
<!-- PROPS                                                              -->
<!-- ═══════════════════════════════════════════════════════════════════ -->

<h2>Test 1: Props ([count], label)</h2>
<wcc-counter id="test1" [count]="propCount" label="Static Label"></wcc-counter>
<p>Angular propCount: {{ propCount }}</p>

<!-- ═══════════════════════════════════════════════════════════════════ -->
<!-- EVENTS                                                             -->
<!-- ═══════════════════════════════════════════════════════════════════ -->

<h2>Test 2: Events ((count-changed))</h2>
<wcc-counter id="test2" [count]="eventCount" (count-changed)="onCountChanged($event)"></wcc-counter>
<p>Angular eventCount: {{ eventCount }}</p>
<button (click)="eventCount = eventCount + 1">Angular increment (manual)</button>

<!-- ═══════════════════════════════════════════════════════════════════ -->
<!-- TWO-WAY BINDING                                                    -->
<!-- ═══════════════════════════════════════════════════════════════════ -->

<h2>Test 3: Two-way binding ([(count)] via plugin)</h2>
<wcc-counter id="test3" [count]="modelCount" (countChange)="modelCount = $any($event).detail"></wcc-counter>
<p>Angular modelCount: {{ modelCount }}</p>
<button (click)="modelCount = modelCount + 1">Angular increment (two-way)</button>

<h2>Test 4: Multiple two-way bindings</h2>
<!-- N/A: v-model.number modifier — Angular no tiene modifiers en [()] -->
<wcc-counter id="test4" [count]="multiCount" (countChange)="multiCount = $any($event).detail" label="Multi-test"></wcc-counter>
<p>Angular multiCount: {{ multiCount }}</p>

<!-- ═══════════════════════════════════════════════════════════════════ -->
<!-- DEFAULT SLOT                                                       -->
<!-- ═══════════════════════════════════════════════════════════════════ -->

<h2>Test 5: Default slot (children)</h2>
<wcc-card id="test5">
  <p>Body content via default slot</p>
</wcc-card>

<!-- ═══════════════════════════════════════════════════════════════════ -->
<!-- NAMED SLOTS                                                        -->
<!-- ═══════════════════════════════════════════════════════════════════ -->

<h2>Test 6: Named slots (ng-template[slot] — WccSlotsDirective)</h2>
<wcc-card id="test6" wccSlots>
  <ng-template slot="header"><strong>Header via ng-template</strong></ng-template>
  <p>Body content</p>
  <ng-template slot="footer">Footer via ng-template</ng-template>
</wcc-card>

<h2>Test 7: Named slots (div slot="name")</h2>
<!-- N/A: v-slot:name — Angular no tiene esa sintaxis, usa ng-template[slot] (Test 6) -->
<wcc-card id="test7">
  <div slot="header"><strong>Bold</strong> header with <em>emphasis</em></div>
  <p>Body content</p>
  <div slot="footer">Footer with <a href="#">link</a></div>
</wcc-card>

<!-- ═══════════════════════════════════════════════════════════════════ -->
<!-- SCOPED SLOTS                                                       -->
<!-- ═══════════════════════════════════════════════════════════════════ -->

<h2>Test 8: Scoped slot (ng-template[slot] let-item let-index)</h2>
<wcc-list id="test8" wccSlots>
  <ng-template slot="item" let-item let-index="index">
    <li><strong>{{ index }}</strong>: {{ item }}</li>
  </ng-template>
</wcc-list>

<h2>Test 9: Scoped slot — custom class</h2>
<wcc-list id="test9" wccSlots>
  <ng-template slot="item" let-item>
    <li class="custom">★ {{ item }}</li>
  </ng-template>
</wcc-list>

<h2>Test 10: Scoped slot + Angular interpolation coexistence</h2>
<wcc-list id="test10" wccSlots>
  <ng-template slot="item" let-item>
    <li>{{ item }} (Angular says: {{ angularMessage }})</li>
  </ng-template>
</wcc-list>

// framework-integrations/vue/src/App.vue
<template>
  <h1>WCC Vue Integration Tests</h1>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- PROPS                                                              -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 1: Props (:count, label)</h2>
  <wcc-counter id="test1" :count="propCount" label="Static Label"></wcc-counter>
  <p>Vue propCount: {{ propCount }}</p>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- EVENTS                                                             -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 2: Events (@count-changed)</h2>
  <wcc-counter id="test2" :count="eventCount" @count-changed="eventCount = $event.detail"></wcc-counter>
  <p>Vue eventCount: {{ eventCount }}</p>
  <button @click="eventCount++">Vue increment (manual)</button>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- TWO-WAY BINDING (v-model)                                          -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 3: v-model:count (plugin)</h2>
  <wcc-counter id="test3" v-model:count="modelCount"></wcc-counter>
  <p>Vue modelCount: {{ modelCount }}</p>
  <button @click="modelCount++">Vue increment (v-model)</button>

  <h2>Test 4: v-model.trim (modifier)</h2>
  <wcc-counter id="test4" v-model:count.number="trimCount"></wcc-counter>
  <p>Vue trimCount: {{ trimCount }} (type: {{ typeof trimCount }})</p>

  <h2>Test 4b: Multiple v-model on same element</h2>
  <wcc-counter id="test4b" v-model:count="multiCount" v-model:label="multiLabel"></wcc-counter>
  <p>Vue multiCount: {{ multiCount }}, multiLabel: {{ multiLabel }}</p>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- DEFAULT SLOT                                                       -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 5: Default slot (children)</h2>
  <wcc-card id="test5">
    <p>Body content via default slot</p>
  </wcc-card>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- NAMED SLOTS                                                        -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 6: Named slots (template #name)</h2>
  <wcc-card id="test6">
    <template #header><strong>Header via #</strong></template>
    <p>Body content</p>
    <template #footer>Footer via #</template>
  </wcc-card>

  <h2>Test 7: Named slots (div slot="name")</h2>
  <wcc-card id="test7">
    <div slot="header"><strong>Bold</strong> header with <em>emphasis</em></div>
    <p>Body content</p>
    <div slot="footer">Footer with <a href="#">link</a></div>
  </wcc-card>

  <h2>Test 8: Named slots (template v-slot:name)</h2>
  <wcc-card id="test8">
    <template v-slot:header><strong>Header v-slot</strong></template>
    <p>Body content</p>
    <template v-slot:footer>Footer v-slot</template>
  </wcc-card>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- SCOPED SLOTS                                                       -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 9: Scoped slot (template #item="{ item, index }")</h2>
  <wcc-list id="test9">
    <template #item="{ item, index }">
      <li><strong>{{ index }}</strong>: {{ item }}</li>
    </template>
  </wcc-list>

  <h2>Test 10: Scoped slot (v-slot:item)</h2>
  <wcc-list id="test10">
    <template v-slot:item="{ item }">
      <li class="custom">★ {{ item }}</li>
    </template>
  </wcc-list>

  <h2>Test 11: Scoped slot + Vue interpolation coexistence</h2>
  <wcc-list id="test11">
    <template #item="{ item }">
      <li>{{ item }} (Vue says: {{ vueMessage }})</li>
    </template>
  </wcc-list>
</template>

<script setup>
import { ref } from 'vue'

const propCount = ref(10)
const eventCount = ref(0)
const modelCount = ref(0)
const trimCount = ref(0)
const multiCount = ref(0)
const multiLabel = ref('hello')
const vueMessage = ref('hello from Vue!')
</script>
