// framework-integrations/react/src/App.jsx
import React, { useRef, useState } from 'react'

export default function App() {
  return (
    <div>
      <h1>WCC React Integration Tests</h1>

      {/* ═══════════════════════════════════════════════════════════════════ */}
      {/* PROPS                                                              */}
      {/* ═══════════════════════════════════════════════════════════════════ */}

      <h2>Test 1: Props (count, label)</h2>
      <PropsTest />

      {/* ═══════════════════════════════════════════════════════════════════ */}
      {/* EVENTS                                                             */}
      {/* ═══════════════════════════════════════════════════════════════════ */}

      <h2>Test 2: Events (oncountchanged)</h2>
      <EventsTest />

      {/* ═══════════════════════════════════════════════════════════════════ */}
      {/* TWO-WAY BINDING                                                    */}
      {/* ═══════════════════════════════════════════════════════════════════ */}

      <h2>Test 3: Two-way binding</h2>
      {/* N/A: React no tiene two-way binding nativo con custom elements.
         Se logra manualmente con prop + event handler (ver Test 2). */}
      <p><em>No aplica en React — se resuelve con prop + event (Test 2).</em></p>

      <h2>Test 4: Two-way binding (modifier / multiple)</h2>
      {/* N/A: React no tiene v-model ni [()] — no hay modifiers ni multiple bindings. */}
      <p><em>No aplica en React.</em></p>

      {/* ═══════════════════════════════════════════════════════════════════ */}
      {/* DEFAULT SLOT                                                       */}
      {/* ═══════════════════════════════════════════════════════════════════ */}

      <h2>Test 5: Default slot (children)</h2>
      <wcc-card id="test5">
        <p>Body content via default slot</p>
      </wcc-card>

      {/* ═══════════════════════════════════════════════════════════════════ */}
      {/* NAMED SLOTS                                                       */}
      {/* ═══════════════════════════════════════════════════════════════════ */}

      <h2>Test 6: Named slots (slot="name")</h2>
      <wcc-card id="test6">
        <div slot="header"><strong>Header via slot attr</strong></div>
        <p>Body content</p>
        <span slot="footer">Footer via slot attr</span>
      </wcc-card>

      <h2>Test 7: Named slots (slot="name" — nested elements)</h2>
      <wcc-card id="test7">
        <div slot="header"><strong>Bold</strong> header with <em>emphasis</em></div>
        <p>Body content</p>
        <div slot="footer">Footer with <a href="#">link</a></div>
      </wcc-card>

      <h2>Test 8: Named slots (JSX prop — via React plugin)</h2>
      {/* N/A: v-slot:name — React no tiene esa sintaxis.
         El equivalente es pasar JSX como prop (requiere wccReactPlugin). */}
      <wcc-card id="test8"
        header={<strong>Header via JSX prop</strong>}
        footer={<span>Footer via JSX prop</span>}
      >
        <p>Body content</p>
      </wcc-card>

      {/* ═══════════════════════════════════════════════════════════════════ */}
      {/* SCOPED SLOTS                                                       */}
      {/* ═══════════════════════════════════════════════════════════════════ */}

      <h2>Test 9: Scoped slot (render prop — item + index)</h2>
      <wcc-list id="test9"
        renderItem={(item, index) => <li><strong>{index}</strong>: {item}</li>}
      />

      <h2>Test 10: Scoped slot (render prop — custom class)</h2>
      <wcc-list id="test10"
        renderItem={(item) => <li className="custom">★ {item}</li>}
      />

      <h2>Test 11: Scoped slot + React state coexistence</h2>
      <ScopedWithStateTest />
    </div>
  )
}

function PropsTest() {
  const [propCount] = useState(10)
  return (
    <div>
      <wcc-counter id="test1" count={propCount} label="Static Label"></wcc-counter>
      <p>React propCount: {propCount}</p>
    </div>
  )
}

function EventsTest() {
  const [eventCount, setEventCount] = useState(0)
  return (
    <div>
      <wcc-counter id="test2" count={eventCount} oncountchanged={(e) => setEventCount(e.detail)}></wcc-counter>
      <p>React eventCount: {eventCount}</p>
      <button onClick={() => setEventCount(c => c + 1)}>React increment (manual)</button>
    </div>
  )
}

function ScopedWithStateTest() {
  const [reactMessage] = useState('hello from React!')
  return (
    <wcc-list id="test11"
      renderItem={(item) => <li>{item} (React says: {reactMessage})</li>}
    />
  )
}

// framework-integrations/vue/src/App.vue
<template>
  <h1>WCC Vue Integration Tests</h1>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- PROPS                                                              -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 1: Props (:count, label)</h2>
  <wcc-counter id="test1" :count="propCount" label="Static Label"></wcc-counter>
  <p>Vue propCount: {{ propCount }}</p>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- EVENTS                                                             -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 2: Events (@count-changed)</h2>
  <wcc-counter id="test2" :count="eventCount" @count-changed="eventCount = $event.detail"></wcc-counter>
  <p>Vue eventCount: {{ eventCount }}</p>
  <button @click="eventCount++">Vue increment (manual)</button>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- TWO-WAY BINDING (v-model)                                          -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 3: v-model:count (plugin)</h2>
  <wcc-counter id="test3" v-model:count="modelCount"></wcc-counter>
  <p>Vue modelCount: {{ modelCount }}</p>
  <button @click="modelCount++">Vue increment (v-model)</button>

  <h2>Test 4: v-model.trim (modifier)</h2>
  <wcc-counter id="test4" v-model:count.number="trimCount"></wcc-counter>
  <p>Vue trimCount: {{ trimCount }} (type: {{ typeof trimCount }})</p>

  <h2>Test 4b: Multiple v-model on same element</h2>
  <wcc-counter id="test4b" v-model:count="multiCount" v-model:label="multiLabel"></wcc-counter>
  <p>Vue multiCount: {{ multiCount }}, multiLabel: {{ multiLabel }}</p>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- DEFAULT SLOT                                                       -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 5: Default slot (children)</h2>
  <wcc-card id="test5">
    <p>Body content via default slot</p>
  </wcc-card>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- NAMED SLOTS                                                        -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 6: Named slots (template #name)</h2>
  <wcc-card id="test6">
    <template #header><strong>Header via #</strong></template>
    <p>Body content</p>
    <template #footer>Footer via #</template>
  </wcc-card>

  <h2>Test 7: Named slots (div slot="name")</h2>
  <wcc-card id="test7">
    <div slot="header"><strong>Bold</strong> header with <em>emphasis</em></div>
    <p>Body content</p>
    <div slot="footer">Footer with <a href="#">link</a></div>
  </wcc-card>

  <h2>Test 8: Named slots (template v-slot:name)</h2>
  <wcc-card id="test8">
    <template v-slot:header><strong>Header v-slot</strong></template>
    <p>Body content</p>
    <template v-slot:footer>Footer v-slot</template>
  </wcc-card>

  <!-- ═══════════════════════════════════════════════════════════════════ -->
  <!-- SCOPED SLOTS                                                       -->
  <!-- ═══════════════════════════════════════════════════════════════════ -->

  <h2>Test 9: Scoped slot (template #item="{ item, index }")</h2>
  <wcc-list id="test9">
    <template #item="{ item, index }">
      <li><strong>{{ index }}</strong>: {{ item }}</li>
    </template>
  </wcc-list>

  <h2>Test 10: Scoped slot (v-slot:item)</h2>
  <wcc-list id="test10">
    <template v-slot:item="{ item }">
      <li class="custom">★ {{ item }}</li>
    </template>
  </wcc-list>

  <h2>Test 11: Scoped slot + Vue interpolation coexistence</h2>
  <wcc-list id="test11">
    <template #item="{ item }">
      <li>{{ item }} (Vue says: {{ vueMessage }})</li>
    </template>
  </wcc-list>
</template>

<script setup>
import { ref } from 'vue'

const propCount = ref(10)
const eventCount = ref(0)
const modelCount = ref(0)
const trimCount = ref(0)
const multiCount = ref(0)
const multiLabel = ref('hello')
const vueMessage = ref('hello from Vue!')
</script>
