// framework-integrations/react/src/main.jsx
import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'

// Register WCC components
import './wcc-components/basics/wcc-counter.js'
import './wcc-components/basics/wcc-card.js'
import './wcc-components/basics/wcc-list.js'
import './wcc-components/basics/wcc-dualmodel.js'
import './wcc-components/directives/wcc-conditional.js'
import './wcc-components/directives/wcc-toggle.js'
import './wcc-components/directives/wcc-input.js'
import './wcc-components/directives/wcc-styled.js'
import './wcc-components/composition/wcc-wrapper.js'
import './wcc-components/composition/wcc-parent.js'

createRoot(document.getElementById('root')).render(<App />)

// framework-integrations/angular/src/main.ts
import 'zone.js';
import { bootstrapApplication } from '@angular/platform-browser';
import { provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withHashLocation } from '@angular/router';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';

// Import WCC compiled components
import './wcc-components/basics/wcc-card';
import './wcc-components/basics/wcc-counter';
import './wcc-components/basics/wcc-list';
import './wcc-components/basics/wcc-dualmodel';
import './wcc-components/directives/wcc-conditional';
import './wcc-components/directives/wcc-toggle';
import './wcc-components/directives/wcc-input';
import './wcc-components/directives/wcc-styled';
import './wcc-components/composition/wcc-wrapper';
import './wcc-components/composition/wcc-parent';

bootstrapApplication(AppComponent, {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withHashLocation()),
  ]
}).catch((err) => console.error(err));
